### PR TITLE
Update backend to user number type for consistency, Add query params, Update get current tournament 

### PR DESCRIPTION
**Pull request by madfcat**
I have updated the APIs to use numbers where it makes more sense than to use number in strings.

- tournament creation now returns the whole tournament object
- `get_current_players()` function returns ids from the current logged in sessions
- array of numbers for `userIds`, number for `duration` and array of 2 numbers for `score` in JSON requests
- add `last` query param  to retrieve last tournaments and last matches. Now we can specify how many we want to get.
- add `finished` query param (true/false) to get only the finished matches

### CODE REVIEW

**Review by dnapi — APPROVED** [review]
Great changes!  Numbers are great again. The code looks fine to me.

**Comment by nikkxll** [comment]
LGTM, need to connect with frontend and adjust if needed

Two questions by now:
- For users logout could we add an id as a separate key for the convenience?
- Do you have any logged-in state for AI? Is it automatically logged in when the session is started?

**Review by nikkxll — APPROVED** [review]
LGTM
Added some comments though

**Comment by madfcat** [comment]
> * For users logout could we add an id as a separate key for the convenience?

I will add it now. We can have it in the next PR. But for now just merge it from `madfcat/backend` branch.

> * Do you have any logged-in state for AI? Is it automatically logged in when the session is started?

AI has no logged in state. It's id is considered to be `1` and it is excluded from sessions check.

**Pull request merged**
