### PR TITLE
Initial draft for Madfcat/backend

### PR DESCRIPTION
**Pull request by madfcat**
Added 1 endpoint for API.
User creation. Player model is extending built-in User model in Django.
Also, when the Player record is removed, a User is removed as well.
The Player has display name and will have avatar in the future.

The idea is to use the built-in Django authentication. That's why the Player model is built on top of the User model.

To test:

```
docker compose up
```

Go to:
http://localhost:8000/admin/

login: admin
password: adminpassword

Credentials can be changed from `.env`

To create a user check the attached screenshot.
image

### CODE REVIEW

**Comment by DaveeHorvath** [comment]
nvm, i have the stupid, i was the one pushing those, mb.

**Comment by DaveeHorvath** [comment]
If possible we shouldnt push the .env file. Its fine for the time being but would be a fail on the project

**Comment by madfcat** [comment]
> If possible we shouldnt push the .env file. Its fine for the time being but would be a fail on the project

Sure. I just left .env for now, so it is easier to setup and test.

**Comment by madfcat** [comment]
> nvm, i have the stupid, i was the one pushing those, mb.

I can add more to `.gitignore`,
but also there are 
```
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
```
in the `Dockerfile`, which should help to not bloat the container.

Quick chat explanation:
image

**Comment by nikkxll** [comment]
Did you discuss the idea of using Django built-in authentication with @taoramo?
As I understood, Taavi is doing 42API Auth and it would be great if both of you were aware and synchronized on this matter

**Comment by madfcat** [comment]
> Did you discuss the idea of using Django built-in authentication with @taoramo?
> 
> As I understood, Taavi is doing 42API Auth and it would be great if both of you were aware and synchronized on this matter

I have not studied it much and we have not discussed anything yet. But it is possible to use custom 3rd party service to authenticate in Django. I think we will sync at some point. I might need to add authentication endpoint. Should be the next step. Just wanted to get things rolling a bit 😉

**Comment by nikkxll** [comment]
But what about ```.env```?
Maybe it would be better to have it in our discord chat rather than here?

**Comment by madfcat** [comment]
I have removed `.env` from all the commit commits, added it to `.gitignore`.
Also, added `.DS_Store` to `.gitignore`.
Removed image from `backend` service as it was trying to pull image from dockerhub first. Now it sets image name automatically.

Btw, I also have
`backend/api-test.json` and `backend/api-test.paw` (files with API endpoints tests). Should I remove them from commits as well?

**Review by nikkxll — COMMENTED** [review]
All good. 
`.env` deleted, user creation tested using endpoints and checked on Django administration platform

**Review by nikkxll — APPROVED** [review]
All good.
.env deleted, user creation tested using endpoints and checked on Django administration platform

**Pull request merged**
