### PR TITLE
Big user management REST API update

### PR DESCRIPTION
**Pull request by madfcat**
## Description

RESTful API implementation
Changed directories structure (`players` Django app is now called `api`)
Changed Friend model to Friendship model
Added custom sessions. Now possible to have as many session as we need.

Added decorators which can authenticate Django views (endpoint functions). `session_authenticated_logged_in` and `session_authenticated_id`.
`session_authenticated_logged_in` is used if there is any logged in session available. For example, for requesting user list or some other information.
`session_authenticated_id` is used to check if user is authenticated to use current endpoint. For example, for updating user information or requesting friendship. Usually, this endpoints have `{id}` in it.

Online/Offline status moved to Player model. For this partm `LastActiveMiddleware` middleware created. Each request with a login session updates `last_active_at` field of Player model. More than 5 minutes of inactivity considered as Offline status.
Added docs for the endpoints to `README.md`

Done so far for the user management module (in terms of endpoints):
- Users can subscribe to the website in a secure way.
- Registered users can log in in a secure way.
- Users can select a unique display name to play the tournaments.
- Users can update their information.
- Users can upload an avatar, with a default option if none is provided.
- Users can add others as friends and view their online status.

### On MacOs

You can use RapiAPI client. It is free for use. Just open `api-test.paw` file

You can check the changes from the admin `https://localhost/admin/`

1. Call API requests `Create User tony`, `Create User mary` to create 2 users.
1. In the RapidAPI client, open Environment variables. Change `Tony Id` to the `id` return from the user creation call. It should be `2` for `Tony Id` and `3` for `Mary Id`, if you are starting with fresh DB.
1. You can now call different requests from the list.
[api-test.paw.zip](https://github.com/user-attachments/files/17422017/api-test.paw.zip)

### On Linux / Windows

Not 100% sure if it works correctly as I have not tested. I exported all request for Postman.
I can try other export. Please, let me know what is your client and it might be possible to export it.
[api-test.paw.json](https://github.com/user-attachments/files/17422049/api-test.paw.json)

### Env variables for the API Client:

Protocol: `https`
Host: `localhost`
Base Url: `Protocol`://`Host`/api/
Tony Id: `2`
Mary Id: `3`

### CODE REVIEW

**Comment by taoramo** [comment]
Had a quick look, seems fantastically legit, great job. Once this is merged I'll make sure everything works nicely with 42auth and session cookie handling, avatar upload etc. The 42auth logic will be very slightly different since using one button it will automatically either make a user and login or just login if user exists. 

We should agree on how to block different login methods from accessing the same user. Maybe just store the original user creation method in Player?

**Review by taoramo — APPROVED** [review]
To my untrained eye all of this looks very good. As I said before, I'll update the 42auth parts to have the same shape as built in login once this is merged.

**Review by DaveeHorvath — APPROVED** [review]
Nice work, the tests seem to work on my side as well. The session decorators look good, we will need to see how they fit into the idea of the lobby. Will need to reference Dimitris new design for that to be confirmed

**Comment by madfcat** [comment]
> To my untrained eye all of this looks very good. As I said before, I'll update the 42auth parts to have the same shape as built in login once this is merged.

👌

> We should agree on how to block different login methods from accessing the same user. Maybe just store the original user creation method in Player?

As a variant, we can add email and authenticate the same user with both ways if email is the same.
Or just store in db if the user was created with 42auth. Ask to add password on 42 auth user creation. Then it can be authenticated both ways.
Users registered with standard way will not be able to authenticate themselves with 42auth.
Maybe email is a way to go?



> Nice work, the tests seem to work on my side as well. The session decorators look good, we will need to see how they fit into the idea of the lobby. Will need to reference Dimitris new design for that to be confirmed

🙌 Yes, let's wait for the design. If any questions, please, write in our Discord group.

**Review by nikkxll — APPROVED** [review]
Everything is clean and to the point. Good job!
I would only suggest to split views on different files

The next step is to discuss how can we integrate it with the frontend and what changes need to be made to the current state of the design.

**Pull request merged**
