### PR TITLE
David/evil

### PR DESCRIPTION
**Pull request by DaveeHorvath**
A quick idea, feel free to reject, but how about adding the about page as the github, and settings as /admin, since we dont really do customisation? Also contains some fixes for history related issues, but can separate if needed

### CODE REVIEW

**Comment by nikkxll** [comment]
I couldn't run it, web page does not work for some reason

**Comment by madfcat** [comment]
> I couldn't run it, web page does not work for some reason

I swapped 8443 to 443 in `nginx.conf` and `docker-compose.yml` and it works.

**Review by nikkxll — CHANGES_REQUESTED** [review]
Since we are not using scripts.js anymore, could you please move the functionality (only the one you've added) to the new file so we could move it to the js folder later on? You can check the current master's structure

One more thing is that we are not using window["loggedinUsers"] anymore, instead we stick to the window.state.loggedInUsers from state.js. These also should be changed I think

**Comment by DaveeHorvath** [comment]
> Since we are not using scripts.js anymore, could you please move the functionality (only the one you've added) to the new file so we could move it to the js folder later on? You can check the current master's structure
> 
> One more thing is that we are not using window["loggedinUsers"] anymore, instead we stick to the window.state.loggedInUsers from state.js. These also should be changed I think

I ended up merging main into it, not sure what its missing then

**Comment by DaveeHorvath** [comment]
we can just remove scripts.js, I moved the required part into its own in the lastest commit, please re-review

**Review by nikkxll — APPROVED** [review]
Might need to modify redirs on "About" and "Settings" buttons, other than that lgtm

**Review by madfcat — APPROVED** [review]
Let's go!

**Pull request merged**
