### PR TITLE
Madfcat/recent matches component

### PR DESCRIPTION
**Pull request by nikkxll**
Added new functionality:
- Recent matches container with fetch
- Recent tournament container with fetch (need to add carousel)
- Mini profiles after login/signup
- Real users now appear in single game and tournament lobby
- Profile first draft (you can discover it by clicking on "Profile" button after login)

DO NOT USE nikkxll/new-fetches-to-front anymore since it is merged with the branch and will be pulled by master !!!

### CODE REVIEW

**Review by DaveeHorvath — APPROVED** [review]
The bootstrap include will need to get included at some point, otherwise clean

**Review by madfcat — APPROVED** [review]
Breaking js into separate files make the code easier to read. Well done!

**Review by dnapi — APPROVED** [review]
Everything looks  fine to me.

**Review by madfcat — APPROVED** [review]
LGTM

**Pull request merged**
