### PR TITLE
helpful comments added

### PR DESCRIPTION
**Pull request by DaveeHorvath**
This is the commented version of the base game code, only notable change are the commnets, chunks of this can be moved to functions. Its somewhat ugly with big functions, but most of them dont require further updates or changes, so time spent isnt really worth it, as this is not a long term project. If certain parts need clarification, please mark it as such

### CODE REVIEW

**Review by dnapi — APPROVED** [review]
All clear and fine!

**Comment by madfcat** [comment]
@DaveeHorvath 

I would use camelCase for the variable names:
`playergeometry` -> `playerGeometry` 
`playermaterial` -> `playerMaterial`
`player1outline` -> `player1Outline`
`outerboxes` -> `outerBoxes`
etc

For example, here you have it correct:
`const ballMesh = new THREE.BoxGeometry(0.5, 0.5, 0.5)`

Please, consider sticking to one name convention and refactor this part as well in the future commits.

**Comment by dnapi** [comment]
Good point ! In AI part I use camelCase .

**Comment by DaveeHorvath** [comment]
Absolutely, sorry for the weird naming. Will reopen and rename tmrw

**Pull request merged**
